-- ============================================================
-- Intersection of "partition ideals" over all set partitions
-- of {1,...,n} whose block-size multiset equals a fixed
-- integer partition lambda of n.
--
-- Convention used here:
--   For a set partition pi = {B_1,...,B_k} of {1,...,n}, the
--   associated ideal I_pi is generated by all differences
--       x_i - x_j    for i,j in the same block B_l.
--   (I_pi is the linear ideal defining the subspace where
--    coordinates in each block are forced equal.)
--
--   Given an integer partition lambda = (lambda_1 >= ... >= lambda_k)
--   of n, we range over ALL set partitions pi of {1,...,n} whose
--   block sizes are exactly the multiset lambda, and compute
--       I_lambda := intersection of I_pi over all such pi.
--
-- Change the definitions of n and lambda below and run the file.
-- ============================================================

n = 5
lambda = {2,2,1}          -- must satisfy sum lambda == n

R = QQ[x_1..x_n]

-- Recursively generate all set partitions of the list S (of integers)
-- whose block-size multiset equals `sizes` (a list of positive integers).
-- Each set partition is returned as a list of blocks; each block is a
-- list of integers. Each unordered set partition appears exactly once:
-- at each step we determine the block containing the smallest
-- remaining element, which fixes a canonical order and avoids
-- duplicate counting from blocks of equal size.
setPartitionsOfType = (S, sizes) -> (
    if #S == 0 then (
        if #sizes == 0 then {{}} else {}
    )
    else (
        e := min S;
        rest := delete(e, S);
        distinctSizes := unique sizes;
        result := {};
        for s in distinctSizes do (
            if s - 1 <= #rest then (
                for T in subsets(rest, s-1) do (
                    block := prepend(e, T);
                    remainingElems := select(rest, i -> not member(i, T));
                    idx := position(sizes, i -> i == s);
                    remainingSizes := drop(sizes, {idx,idx});
                    for P in setPartitionsOfType(remainingElems, remainingSizes) do (
                        result = append(result, prepend(block, P));
                    );
                );
            );
        );
        result
    )
)

-- Build the ideal I_pi for a given set partition pi (list of blocks)
partitionIdeal = (P) -> (
    gensList := {};
    for block in P do (
        if #block > 1 then (
            for i from 1 to #block - 1 do (
                gensList = append(gensList, x_(block#0) - x_(block#i));
            );
        );
    );
    if #gensList == 0 then ideal(0_R) else ideal(gensList)
)

-- All set partitions of {1,...,n} of type lambda
allPartitions = setPartitionsOfType(toList(1..n), lambda);
print(concatenate("Number of set partitions of type ", toString lambda,
    ": ", toString(#allPartitions)));

-- Ideal for each set partition
idealsList = apply(allPartitions, partitionIdeal);

-- The desired intersection
I = intersect(idealsList)

-- Optional: a minimal/reduced Groebner basis
gens gb I
