from partitions import *
from expressions import *
import math
from math import comb
import sympy as sp
t = sp.symbols('t')
from random import randrange
import sys
import itertools

# hilbert series of I_mu, where mu is a partition
def specht_hilbert_series(mu: Partition):    
    recursive_partitions = PartitionSet([mu]) # this set holds the partitions that will be involved in the recursion
    new_partitions = PartitionSet([mu]) # this set holds the partitions that still need to be processed (we need to store the partitions that are involved with their Hilbert series)
    while len(new_partitions.partitions) != 0:
        p = new_partitions.partitions[0]
        for i in range(1, len(p) + 1):
            for g in lower_ideal_generators(p, i):
                success = recursive_partitions.add_partition(g)
                if success:
                    new_partitions.add_partition(g)
        new_partitions.remove_partition(p)

    hilbert_series = {} # this dictionary stores the hilbert series of all partitions in recursive_partitions
    for p in reversed(recursive_partitions.partitions):
        if len(p) == 1:
            hilbert_series[p] = HilbExpr(0)
            continue
        if p[1] == 1:
            hilbert_series[p] = HilbExpr(1 - t**(math.comb(sum(p), 2)), sum(p), simplify=True)
            continue

        hs = HilbExpr(0)
        for i in range(1, len(p)):
            gens = lower_ideal_generators(p, i)
            if len(gens) == 1:
                hs += HilbExpr(t**(i - 1)) * hilbert_series[gens[0]]
            else:
                hs += HilbExpr(t**(i - 1)) * (hilbert_series[gens[0]] + hilbert_series[gens[1]] - hilbert_series[gens[2]])
        gens = lower_ideal_generators(p, len(p))
        if len(gens) == 1:
            hs += HilbExpr(t**(len(p) - 1), 1) * hilbert_series[gens[0]]
        else:
            hs += HilbExpr(t**(len(p) - 1), 1) * (hilbert_series[gens[0]] + hilbert_series[gens[1]] - hilbert_series[gens[2]])
        hilbert_series[p] = hs

    return hilbert_series[mu]

# hilbert series of I_L, where L is a lower order ideal
def ideal_specht_hilbert_series(L: LowerOrderIdeal):
    # base cases
    if len(L.generators) == 1:
        return specht_hilbert_series(L.generators[0])
    if len(L.partitions) == 0:
        return HilbExpr(1, L.n) 

    hs = HilbExpr(0)
    max_len = max([len(g) for g in L.generators])
    for i in range(max_len - 1):
        hs += HilbExpr(t**i)  * ideal_specht_hilbert_series(L.smaller_ideal(i + 1))
    hs += HilbExpr(t**(max_len - 1), 1) * ideal_specht_hilbert_series(L.smaller_ideal(max_len))
    return hs

# hilbert series of I_mu / I_(<mu), the module discussed in the Haiman-Woo manuscript
def haiman_woo_hilbert_series(mu: Partition):    
    I = mu.strictly_less_than_ideal()
    return ideal_specht_hilbert_series(I) - specht_hilbert_series(mu)

# generators of L_i, where L is the lower order ideal generated by the partion mu
def lower_ideal_generators(mu: Partition, i):
    if len(mu) == 1 or mu[1] == 1:
        return [] # these are base cases for the recursive formula, so we don't consider the generators

    corners = mu.corner_set()
    m = max((x for x in corners if x <= i), default=0)
    ith_part = mu[i]

    if ith_part == 1:
        return [mu.remove_from_part(m)]
    
    ith_compression = mu.compress(i)
    if m == 0 or m == i:
        return [ith_compression.remove_from_part(i)]

    return [mu.remove_from_part(m), ith_compression.remove_from_part(i), ith_compression.remove_from_part(m)]

# for k in range(8):
#     p = Partition([3 + k, 3, 1, 1])
#     print("k:", k, "HS:", specht_hilbert_series(p))

# p = Partition([3, 3, 1])
# print("p:", p, "HS:", specht_hilbert_series(p))
# for k in range(1, len(p) + 1):
#      print("k:", k, "gens:", lower_ideal_generators(p, k))

# a, b, c = 0, 0, 0
# for a in range(0, 6):
#     for b in range(2, 7):
#         info = []
#         for k in range(0,8):
#             p = Partition([2 + k] + [2]*(b-1) + [1]*a)
#             hs = specht_hilbert_series(p)
#             info.append([hs.degree(), hs.LC()])
#         print("a, b, c:", a, b, c, "(deg, l.c.):", info)
#     print("************************************")

# a = 0
# for b in range(3, 4):
#     for c in range(2, 6):
#         p = Partition([4] + [3]*(c -1) + [2]*b)
#         hs = specht_hilbert_series(p)
#         pprime = lower_ideal_generators(p, len(p) - 1)[2]
#         hsprime = specht_hilbert_series(pprime)
#         print(p, hs)
#         print()
#         print(pprime, hsprime)
#         print("************************************************")

# for lam3 in range(2,8):
#     for lam2 in range(lam3, lam3+4):
#         for lam1 in range(lam2, lam2+4):
#             for alen in range(5,9):
#                 p = Partition([lam1, lam2, lam3] + [1]*(alen-3))
#                 guess = comb(len(p),2) + p[1]*(len(p) - 2) + p[2]*(len(p)-1) + p[3]*(len(p)-1) - 3*len(p) + 3
#                 print(specht_hilbert_series(p).degree(), guess, p)

# for p in Partitions(15):
#     if p[1] > 1:
#         p = Partition(p.parts + [1,1])
#         guess = comb(len(p),2) + (len(p) - 2)*p[1] + (len(p) - 1)*(sum(p[i] - 1 for i in range(2, len(p) + 1)) - 1)
#         print(specht_hilbert_series(p).degree(), guess, p) 

# for k in range(0, 10):
#     p = Partition([2 + k, 2, 2, 2, 2, 2, 1, 1])
#     print("k:", k, "Hilb Ser:", specht_hilbert_series(p))
#     print()

# p = Partition([2, 2, 2, 1, 1, 1, 1])
# print(specht_hilbert_series(p))
# for k in range(1, len(p) + 1):
#     print("k:", k, "gens:", lower_ideal_generators(p, k))

# for k in range(0, 8):
#     p = Partition([3 + k, 1, 1, 1])
#     q = Partition([2 + k, 2, 2])
#     L = LowerOrderIdeal(6 + k, [p, q])
#     print(ideal_specht_hilbert_series(L))
#     I = L.smaller_ideal(2)
#     print(I)
#     print(ideal_specht_hilbert_series(I))
#     print(specht_hilbert_series(p))
#     print(specht_hilbert_series(q))
#     print("*************************************")

def formula(p):
    w = len(p)
    deg = 0
    deg += (w - 2)*p[1]
    deg += (w - 1)*(sum(p) - p[1])
    if w - p[w] + 1 >= 2:
        deg -= comb(w - p[w] + 1, 2)
    return deg

def recursive_terms(p):
    for i in range(1, len(p) + 1):
        print("*******", i, "*********")
        gens = lower_ideal_generators(p, i)
        for gen in gens:
            hs = specht_hilbert_series(gen)
            print("Partiion:", gen, "Deg:", hs.degree(), "LC:", hs.LC())
    print("**************")

def find_stabilization(p):
    parts = p.parts.copy()
    curr_hil_ser = specht_hilbert_series(p)
    curr_deg = curr_hil_ser.degree()
    curr_lc = curr_hil_ser.LC()
    curr_deg_guess = formula(p)

    stabilization_not_found = True
    k = 0
    while stabilization_not_found:
        parts[0] += 1
        new_p = Partition(parts)
        new_hil_ser = specht_hilbert_series(new_p)
        new_deg = new_hil_ser.degree()
        new_lc = new_hil_ser.LC()
        new_deg_guess = formula(new_p)

        if new_deg - curr_deg == len(p) - 2:
            print(p, "chain stabilized at k =", k)
            print("Degree:", curr_deg)
            print("Formula Guess:", curr_deg_guess)
            print("LC:", curr_lc)
            print("Next LC:", new_lc)
            break

        k += 1
        curr_hil_ser = new_hil_ser
        curr_deg = new_deg
        curr_lc = new_lc
        curr_deg_guess = new_deg_guess


# p = Partition([18, 4, 4, 4])
# deg = specht_hilbert_series(p).degree()
# guess = formula(p)
# print(p, specht_hilbert_series(p).degree(), guess)

# for j in range(100):
#     parts = []
#     for k in range(randrange(2, 5)):
#         parts.append(randrange(2, 9))
#     p = Partition(parts)
#     print("****************")
#     for i in range(10):
#         new_parts = p.parts.copy()
#         new_parts[0] += i
#         q = Partition(new_parts)
#         deg = specht_hilbert_series(q).degree()
#         guess = formula(q)
#         print(q, deg, guess)
#         if guess == deg:
#             print("YIPPPPEEEE")
#             break
#         if i == 9:
#             print("GULLLLP")
#             sys.exit(1)
        

# for j in range(10):
#     parts = []
#     for i in range(4):
#         parts.append(randrange(4, 7))
#     parts.append(4)
#     parts[0] += 4
#     p = Partition(parts)
#     deg = specht_hilbert_series(p).degree()
#     guess = formula(p)
#     print(p, specht_hilbert_series(p).degree(), guess)

# print(list(itertools.combinations_with_replacement(range(1, 5), 4)))

find_stabilization(Partition([6, 2, 2, 2, 2, 1, 1, 1]))

recursive_terms(Partition([6, 2, 2, 2, 2, 1, 1, 1]))

# for n in range(2, 21):
#     for p in Partitions(n):
#         if len(p) == 7 and p[1] == p[2] and p[2] == 2:
#             find_stabilization(p)
#             print("*******************")

# for combos in list(itertools.combinations_with_replacement(range(1, 5), 4)):
#     parts = list(combos)
#     parts.sort(reverse=True)
#     if parts[0] == parts[1]:
#         for k in range(8):
#             p = Partition(parts)
#             deg = specht_hilbert_series(p).degree()
#             guess = formula(p)
#             print(p, deg, specht_hilbert_series(p).LC())
#             parts[0] += 1
#         print("**************************")

# p = Partition([9, 5, 4])
# deg = specht_hilbert_series(p).degree()
# guess = formula(p)
# print(p, specht_hilbert_series(p).degree(), specht_hilbert_series(p).LC())

# p = Partition([8, 4, 4])
# deg = specht_hilbert_series(p).degree()
# guess = formula(p)
# print(p, specht_hilbert_series(p).degree(), specht_hilbert_series(p).LC())

# p = Partition([9, 4, 4])
# deg = specht_hilbert_series(p).degree()
# guess = formula(p)
# print(p, specht_hilbert_series(p).degree(), specht_hilbert_series(p).LC())

# p = Partition([8, 5, 3])
# deg = specht_hilbert_series(p).degree()
# guess = formula(p)
# print(p, specht_hilbert_series(p).degree(), specht_hilbert_series(p).LC())

# p = Partition([9, 5, 3])
# deg = specht_hilbert_series(p).degree()
# guess = formula(p)
# print(p, specht_hilbert_series(p).degree(), specht_hilbert_series(p).LC())
